version: "3.9"

services:
    app:
        build: .
        container_name: node_app
        restart: always
        ports:
            - "3010:3000"
        environment:
            - RABBITMQ_URL=amqp://rabbitmq
        depends_on:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5680:5672" # RabbitMQ main port
            - "15800:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: pass
